services:
  paint_diary:
    build: .
    container_name: paint_diary
    restart: always

    ports:
      - "8000:8000"

    environment:
      DASHSCOPE_API_KEY: ${DASHSCOPE_API_KEY}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_DEFAULT_REGION: ap-northeast-2
